### ISSUE TITLE
regex bug

### ISSUE THREAD

**Issue by prashant-saxena** [jfstn/Validator#14]
Hi,

I have a rule defined like this:

`'tags': ['required','between:3,100','regex:/^[a-z0-9, ]+$/'], `

The problem is because of comma ',' character. In validateMatch function, where
`let re = params[0]`

line is there, actual param value is
`Array [ "/^[a-z0-9", " ]+$/" ]`

and you are using param[0], that's why it's throwing 

> unterminated character class

error.

**Comment by jfstn** [comment]
This will not be fixed. You are free to open a PR anyway.
