### ISSUE TITLE
Date rule is implicitly required

### ISSUE THREAD

**Issue by ferrao** [jfstn/Validator#15]
The following code should validate and not print any errors:

```
let v = Validator.make({}, { date: 'date' });
if (v.fails()) {
    let errors = v.getErrors()
    console.log(errors)
}
```

But the following ouput is produced: 

`{ date: [ 'The date is not a valid date.' ] }`

**Comment by ToxicLord** [comment]
Not only with dates, but with any other type of data

`const rules = {
    data : 'alpha'
}
const validatorTest = Validator.make({}, rules)

if(validatorTest.fails()){
    console.log(validatorTest.getErrors());
} else {
    console.log('It\'s all fine and dandy');
}`

The output produced is: 

`{ data: [ 'The data may only contain letters.' ] }`

**Comment by jfstn** [comment]
@Robinz250 you are free to open a PR to solve the issue.
