### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by oscarvegar** [jfstn/Validator#18]
Hi, new domain extensions have more than 4 digits, example  domain.rocks, backbone.studio, etc. This REGEX needs to be updated.

Line 805 of Validator.js

return this.validateMatch(name, value, /^[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,4}$/i);

**Comment by jfstn** [comment]
I'll take care of this for the next release. :)

**Comment by jfstn** [comment]
@oscarvegar In v1.0.8 regex was updated to allow email domains with a max of 8 characters.
