### ISSUE TITLE
Conflict module 'Validator' with 'validator'

### ISSUE THREAD

**Issue by Droppix** [jfstn/Validator#19]
Hi,

You have a conflict with the module validator (https://www.npmjs.com/package/validator).
Every time I install a new npm module, the module 'Validator' is replaced by 'validator' (by npm)
I work on mac, the system file doesn't differentiate between lower and upper case.
It would be better if you could rename your module, by another name, but only in lower case like all npm modules.

Regards

**Comment by jfstn** [comment]
Hello @Droppix!

I'll take care of it sooner or later, I'm thinking of rewriting the library and eventually solve that. I had that filesystem problem before and I know what you are talking about. 😅 

Thanks for your feedback!

**Comment by jfstn** [comment]
Due to the way that npm works I will not be renaming the library.
