### ISSUE TITLE
It does not work if "data" value is an empty object.

### ISSUE THREAD

**Issue by AlighaThor** [jfstn/Validator#27]
Hey, good library. I'm very used to Laravel, so this implementation of yours is a good help.

I found probably an issue regarding if "data" is an empty object or not. Right now I'm working with Express, and after noticing that I'm receiving an empty object from req.body, I cannot make the validator fails.

Is this the intended behaviour? If I recall correctly, in Laravel if a Validation.make() instance does not receive a filled value, the fails() method gets called. This is not happening with this implementation. I mean, I think if we are validating some rules against empty/null/undefined data the validator should fail.

Steps to reproduce:
- Create an empty data object.
- Apply it to the validator instancie.
- Call fails() or passes()

Result:
- The expected validation result is misleading.

**Comment by jfstn** [comment]
Hello!

Thanks a lot for your input. That behaviour was recently changed to not fail if validating empty objects. 

As this library is based on Laravel I might revert this decision on the next release. I'll leave this issue open until that new release is published.

**Comment by jfstn** [comment]
Hello 👋

The current behavior will stay as I believe that if no data is present then there is nothing to validate even if that's laravel default behavior. 

If you do not agree with this feel free to tell me. I'll close the issue for now. 

Thanks,
João Faustino

**Comment by AlighaThor** [comment]
Hi Joao. I ended using other validation solution. Thanks. Keep on going with this library. Regards.

**Comment by guyaumetremblay** [comment]
I'm sorry to reply to an old thread but I think this is a bad decision. We just updated our dependency to 1.1.2 and some validations stop working due to this. I'll explain why I think this is a bad decision. 

We'll take one of our situation as an exemple: 

We have a POST request containing only one field. So, our code look like this: 
```javascript
const validator = Validator.make(req.body, {
    foo: "required",
});
```

So, this validation stop working if we receive a call on our endpoint without the only one and required field! 

Now, we need to do something like that: 
```javascript
if (validator.fails() || Object.keys(req.body).length === 0) {
...
}
```
Or just drop the validator...

Could you re-think your decision please?

**Comment by jfstn** [comment]
Let me see If I understood correctly.

1. You are trying to validate an object that should have a `foo` property, therefore `required`.
2. Validations `fails` because an object without that property, `foo` was passed?

Is that it? :)

**Comment by guyaumetremblay** [comment]
No, the validation don't fail now with the latest version, if we pass an
empty object. Even if the object doesn't have the required field, the
validation don't fail (so it's in success which is not true)

Le jeu. 27 mai 2021 21 h 22, João Faustino ***@***.***> a
écrit :

**Comment by jfstn** [comment]
I'll look at this and get back to you this weekend.

**Comment by jfstn** [comment]
I'll revert this decision on the next release.

**Comment by guyaumetremblay** [comment]
@jfstn Thanks a lot 👍

**Comment by jfstn** [comment]
@guyaumetremblay I will release a new version today that fixes this behavior. 

1. If there are no required fields the validation should pass;
2. If there are required fields the validation will fail;

Thank you.
