### ISSUE TITLE
How I can translate the messages?

### ISSUE THREAD

**Issue by neadev** [jfstn/Validator#4]
I like to changes the messages on runtime or translate it. thank you.

**Comment by ratiw** [comment]
@developersoul Sorry, didn't notice that you posted the issue. 

You should be able to provide your custom message by passing it as the third paramerter of `Validator.make()`. See Laravel's doc [here](https://laravel.com/docs/5.2/validation#custom-error-messages).

**Comment by williamfelippe** [comment]
Could you give an example?

I'd tried this way:

```
const messages = {
    'email': ':attr is not valid',
    'required': 'Forgot the  :attr field'
};

const v = Validator.make(data, rules, messages);
```
However, did not work. Thank you

**Comment by ratiw** [comment]
@williamfelippe Just recheck the [code](https://github.com/ratiw/Validator/blob/master/src/Validator.js#L194-L195), it only works for a given attribute, e.g. `name.required`. Will find time to fix that.

**Comment by ratiw** [comment]
@williamfelippe v1.0.4 is out and you should now be able to override message for based rules like `required`, etc.
