### ISSUE TITLE
Validating an array of entries

### ISSUE THREAD

**Issue by Dylan-DPC** [jfstn/Validator#5]
Is it possible to validate an array of entries? 

e.g. if i have an emails array 
[ 'a@a.com' , 'b@b.com', 'a' ]

and want to validate each value using this package

Thanks

**Comment by ratiw** [comment]
@Dylan-DPC Not at the moment. I still didn't have time to update this library.

**Comment by Dylan-DPC** [comment]
ok no issues. If I have time I may send a PR.. is that okay?

**Comment by ratiw** [comment]
@Dylan-DPC That would be grate. 👍

**Comment by FerrielMelarpis** [comment]
@ratiw @Dylan-DPC How do you plan on solving this?
Are we going to follow Laravel's implementation?
e.g.
```js
const data = {
  foo: [
    { bar: 1 }.
    { bar: 2 }
  ],
  ...
};

const rules = {
  foo: 'array',
  'foo.*.bar': 'required|numeric'
  ...
};

const v = Validator.make(data, rules);
v.passes(); // true
```
I'm thinking if it is array rule is used, all other rules are applied to each elements.
e.g.
```js
...
const rules = {
  foo: 'array|required|numeric'
  ...
}
```

**Comment by Dylan-DPC** [comment]
yes not a bad idea

**Comment by Dylan-DPC** [comment]
Sorry about this but i'm no longer interested in this feature since I don't use this library any more. If anyone wants this feature, they can open an issue about it. Thanks :)
